library(data.table)
library(dplyr)
setwd('/Users/michelle/Downloads/data/R in coursera/datascience/EDA')
## use paste() to paste the first 2 cols and use strptime()
hpc<-fread('household_power_consumption.txt')
hpc_sub<-filter(hpc,Date == '1/2/2007'|Date == '2/2/2007')
hist(as.numeric(hpc_sub$Global_active_power),col = 'red',main = 'Global Active Power',xlab = 'Global Active Power(kilowatts)')
dev.copy(png,'plot1.png')
dev.off()